// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/apps/chatbot/chat": {
    params: {};
  };
  "/app/proxy/chat": {
    params: {};
  };
  "/auth/shopify/callback": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth" | "/api/chat" | "/apps/chatbot/chat" | "/app/proxy/chat" | "/auth/shopify/callback";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/";
  };
  "routes/api.auth.tsx": {
    id: "routes/api.auth";
    page: "/api/auth";
  };
  "routes/api.chat.tsx": {
    id: "routes/api.chat";
    page: "/api/chat";
  };
  "routes/apps.chatbot.chat.tsx": {
    id: "routes/apps.chatbot.chat";
    page: "/apps/chatbot/chat";
  };
  "routes/app.proxy.chat.tsx": {
    id: "routes/app.proxy.chat";
    page: "/app/proxy/chat";
  };
  "routes/auth.shopify.callback.tsx": {
    id: "routes/auth.shopify.callback";
    page: "/auth/shopify/callback";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/api.auth": typeof import("./app/routes/api.auth.tsx");
  "routes/api.chat": typeof import("./app/routes/api.chat.tsx");
  "routes/apps.chatbot.chat": typeof import("./app/routes/apps.chatbot.chat.tsx");
  "routes/app.proxy.chat": typeof import("./app/routes/app.proxy.chat.tsx");
  "routes/auth.shopify.callback": typeof import("./app/routes/auth.shopify.callback.tsx");
};